  pipeline {
    agent any
    stages {
      stage('Build') {
        steps {
          checkout scm
          sh 'mvn clean package' // Build the backend with Maven
        }
      }
      stage('Build Frontend') {
        steps {
          sh 'cd frontend && npm install && npm run build' // Build the React frontend
        }
      }
      stage('Docker Build') {
        steps {
          sh 'docker build -t my-app .' // Build the Docker image
        }
      }
      stage('Docker Push') {
        steps {
          withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]) {
            sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD' // Log in to Docker Hub
          }
          sh 'docker push my-app' // Push the Docker image to the registry
        }
      }
    }
  }
